server:
  port: 9030

logging:
  level:
    org.springframework.scheduling: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  flyway:
    enabled: true
  application:
    name: scrapper-api
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper_db
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect