CREATE TABLE tg_chats
(
    chat_Id    BIGINT PRIMARY KEY ,
    registered_at TIMESTAMP not null
);

CREATE TABLE stock
(
    id_stock BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT REFERENCES tg_chats (chat_Id) ON DELETE CASCADE,
    ticker  varchar(10) not null
);

CREATE TABLE links
(
    id_link BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id BIGINT REFERENCES tg_chats (chat_Id) ON DELETE CASCADE,
    link varchar(100) not null
)
