CREATE TABLE tg_chats
(
    chat_id       BIGINT PRIMARY KEY,
    registered_at TIMESTAMP NOT NULL
);

CREATE TABLE stock
(
    id_stock    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id     BIGINT REFERENCES tg_chats (chat_id) ON DELETE CASCADE,
    ticker      VARCHAR(10) NOT NULL,
);

CREATE TABLE links
(
    id_link      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id      BIGINT REFERENCES tg_chats (chat_id) ON DELETE CASCADE,
    link         VARCHAR(100) NOT NULL,
    count_answer INT          NOT NULL
);
