server:
  port: 8080

spring:
  application:
    name: telegram-bot

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

telegram:
  bot:
    token: "7674976296:AAHby8eK6974Lpiy2milplojVpB_XbvF0RE"
    username: "LinkHawkBot"
logging:
  level:
    me.ivanmorozov.scrapper.services.api.CheckSubscribeService: DEBUG
    me.ivanmorozov.scrapper.client.StackOverflowClient: TRACE
