server:
  port: 8080

spring:
  kafka:
    admin:
      auto-create: true
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
    consumer:
      group-id: scrapper-api-group
      auto-offset-reset: earliest
      enable-auto-commit: false
  application:
    name: telegram-bot


telegram:
  bot:
    token: "7674976296:AAHby8eK6974Lpiy2milplojVpB_XbvF0RE"
    username: "LinkHawkBot"
logging:
  level:
    me.ivanmorozov.scrapper.services.api.CheckSubscribeService: DEBUG
    me.ivanmorozov.scrapper.client.StackOverflowClient: TRACE
